# Import base_config from git
import_from_git(url: 'https://github.com/rakutentech/ios-buildconfig.git')

default_platform(:ios)

platform :ios do
  desc "Build everything"
  lane :ci do |options|
    swiftlint(
      strict: true,
      ignore_exit_status: false
    )

    cocoapods(repo_update: ENV['REM_FL_CP_REPO_UPDATE'] || false)

    scan(
      clean: true,
      output_directory: './artifacts/unit-tests',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      device: ENV['REM_FL_TESTS_DEVICE'] || 'REM SDK Unit Tests',
      code_coverage: true,
      output_types: 'json-compilation-database,html,junit',
      output_files: 'compile_commands.json,report.html,report.junit')
  end

  desc "Set up environment"
  lane :setup_env do
    # Use env variables to set up endpoints/keys in order to keep them secret
    set_info_plist_value(path: "./Sample/Info.plist",
                         key: "RASApplicationIdentifier",
                         value: ENV['RAS_APPLICATION_IDENTIFIER'] || "APP_ID")
    set_info_plist_value(path: "./Sample/Info.plist",
                         key: "RASProjectSubscriptionKey",
                         value: ENV['RAS_PROJECT_SUBSCRIPTION_KEY'] || "SUBSCRIPTION_KEY")
    set_info_plist_value(path: "./Sample/Info.plist",
                         key: "RRCConfigAPIEndpoint",
                         value: ENV['RRC_CONFIG_API_ENDPOINT'] || "https://config-endpoint.com")
  end

  desc "Generate code coverage locally"
  lane :coverage do |options|
    xcov(
      workspace: 'RRemoteConfig.xcworkspace',
      scheme: 'Tests',
      output_directory: 'artifacts/unit-tests/coverage',
      source_directory: './RRemoteConfig',
      json_report: true,
      include_targets: 'RRemoteConfig.framework',
      include_test_targets: false,
      skip_slack: true,
      disable_coveralls: true
    )
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
